### ISSUE TITLE
[BUG]: Incomplete download

### ISSUE THREAD

**Issue by Umbertumber1122** [nogiszd/xiaomi-note-exporter#10]
**Describe the bug**
The app downloads only my first note.

**Expected behavior**
To download all of the notes

**Screenshots**
![image](https://github.com/nogiszd/xiaomi-note-exporter/assets/137005098/ba9b27a6-7499-4acf-81a4-6e01d5365960)

**Current environment (please complete the following information):**
 - Current Chrome version 114.0.5735.134 {latest)
 - App version 1.1.0

**Comment by Umbertumber1122** [comment]
Btw miło poznać :P

**Comment by nogiszd** [comment]
Hi! Thank you for reporting the issue. 
Indeed, issue was preventing from "unsupported note" callback from working as expected.
This should be fixed in [release v1.1.1](https://github.com/nogiszd/xiaomi-note-exporter/releases/tag/v1.1.1).

Please let me know if this resolves this issue.

PS. Cześć 😄

**Comment by Umbertumber1122** [comment]
Everything works now. Thanks!
