### ISSUE TITLE
[BUG]: It doesn't download all of my notes

### ISSUE THREAD

**Issue by 0ne-zero** [nogiszd/xiaomi-note-exporter#3]
- I tried to download my notes, it recognized the number of notes correctly, but it just downloaded first note and not the rest of notes.
- BTW, thanks for creating this cool tool :)

**Expected behavior**
- I just want to download all of my notes

**Current environment (please complete the following information):**
 - Current Chrome version [e.g. latest]
- My chrome version is:110.0.5481.78
- And i downloaded the same chromedriver version

**Comment by nogiszd** [comment]
Hello @0ne-zero, thank you for reporting this issue.

Did you get any error or it just hung itself up on the second note? 

Also you can delete shipped chromedriver.exe and run program by itself.
Since v1.0.4 it includes selenium-manager which downloads latest driver on runtime.

**Comment by 0ne-zero** [comment]
Thanks for your response :)

No, I didn't get any error, it just shows that it's downloading notes one by one to the last and finally it prints that your note has been saved in "blah-blah" file.
But in the output file, I can just see the first note and some new lines with " **** " characters.
output file content sample:
```text
****
my first note
****

****

****

****

****
```
IMO, I think that maybe the MI Cloud website has changed its UI and the program can't just get the title and text of each note, except the first one.

**Comment by nogiszd** [comment]
Hi, i've looked into it, and that was bug in code. UI of their app hasn't changed.
Program was skipping notes because missing property of object to be found, fix was to check if object was displayed, and not only if was registered in DOM.

[Latest release](https://github.com/nogiszd/xiaomi-note-exporter/releases/latest) addresses this issue.

Please let me know if this update resolved it for you, thanks!

**Comment by nogiszd** [comment]
Stale issue

**Comment by nogiszd** [comment]
Stale issue
